name: Sync Repository Labels

on:
  push:
    branches: [main]
    paths: ['.github/labels/labels.yml']
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  label-sync:
    runs-on: ubuntu-latest
    name: Sync labels with repository
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Sync labels
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels/labels.yml
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          delete: true
          dry-run: false